Added frontend activity diagram
Wilsven/technical-docs pull request #19
Opened 2024-07-19 07:31 UTC by lyndonlim27

2024-07-19 07:37 UTC, TsienJin requested changes

2024-07-19 07:37 UTC, TsienJin commented on docs/projects/genai/health-hub/webapp/frontend/frontend_activity_diagram.md
Hi pls add a H1 header for the name, thanks

2024-07-22 06:38 UTC, lyndonlim27 commented on docs/projects/genai/health-hub/webapp/frontend/frontend_activity_diagram.md
Added as requested. Thanks!

2024-07-22 07:15 UTC, TsienJin approved these changes

2024-07-22 07:17 UTC, merged